Changes for issue "Create background and icon options for display boxes"
code4romania/civiclabs.ro pull request #92
Opened 2020-07-06 14:20 UTC by cosminbosutar

Added  title icon, title background color and title text color for "byproducts" block.
Created a new "custom byproduct" block that displays only 1 byproduct and has the following options: title, width, title icon, title background color and title text color.

2020-07-07 21:41 UTC, andreiio requested changes

2020-07-07 21:41 UTC, andreiio commented on resources/views/admin/blocks/byproducts.blade.php
> +    ]
Cred că ar fi mai ușor de gestionat pe viitor dacă ai extrage lista de icons într-un `config/icons.php`:

```php
return [
    '3d_rotation',
    'accessibility',
    ...
];
```

și să compui opțiunile în block așa:

```php
'options' => collect(config('icons'))
    ->map(function($icon) {
        return ['value' => $icon, 'label' => $icon];
    })
    ->prepend(['value' => '', 'label' => 'no icon'])
    ->toArray(),
```

2020-07-07 21:41 UTC, andreiio commented on resources/views/admin/blocks/custombyproduct.blade.php
> +    ]
Aceeași sugestie ca mai sus, ca să menținem o singură definiție a listei de icons.

2020-07-08 11:24 UTC, cosminbosutar commented on resources/views/admin/blocks/custombyproduct.blade.php
> +    ]
done

2020-07-08 11:25 UTC, cosminbosutar commented on resources/views/admin/blocks/byproducts.blade.php
> +    ]
done

2020-07-08 14:28 UTC, andreiio approved these changes

2020-07-08 14:28 UTC, merged